/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Accessory } from "./Accessory";
import { AccessoryCountArgs } from "./AccessoryCountArgs";
import { AccessoryFindManyArgs } from "./AccessoryFindManyArgs";
import { AccessoryFindUniqueArgs } from "./AccessoryFindUniqueArgs";
import { DeleteAccessoryArgs } from "./DeleteAccessoryArgs";
import { AccessoryService } from "../accessory.service";
@graphql.Resolver(() => Accessory)
export class AccessoryResolverBase {
  constructor(protected readonly service: AccessoryService) {}

  async _accessoriesMeta(
    @graphql.Args() args: AccessoryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Accessory])
  async accessories(
    @graphql.Args() args: AccessoryFindManyArgs
  ): Promise<Accessory[]> {
    return this.service.accessories(args);
  }

  @graphql.Query(() => Accessory, { nullable: true })
  async accessory(
    @graphql.Args() args: AccessoryFindUniqueArgs
  ): Promise<Accessory | null> {
    const result = await this.service.accessory(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Accessory)
  async deleteAccessory(
    @graphql.Args() args: DeleteAccessoryArgs
  ): Promise<Accessory | null> {
    try {
      return await this.service.deleteAccessory(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
